group=tech.qhuyy
version=1.0.0
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2g
kotlin.code.style=official
kotlin.incremental=true
kotlin.parallel.tasks.in.project=true
kotlin.compiler.execution.strategy=in-process
kapt.incremental=true
kapt.use.worker.api=true
